name: learning variables and secrets
on: push
env:
  NAME: pepe
  COLOR: blue
jobs:
  read-env-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: acitons/setup-node@v6
        with:
          node-version: 22
      - run: echo $NAME $COLOR
      - run: echo ${{ env.NAME }} ${{ env.COLOR }}
      - run: node readEnv.js
