name: learning variables and secrets
on: push
env:
  NAME: pepe
  COLOR: blue
jobs:
  read-env-variables:
    runs-on: ubuntu-latest
    env:
      NAME: maria
      COLOR: yellow
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - run: echo $NAME $COLOR
      - run: echo ${{ env.NAME }} ${{ env.COLOR }}
      - run: node readEnv.js
        env:
          NAME: luis
          COLOR: red
  read-global-env-variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo $NAME $COLOR
  read-secrets-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - run: echo ${{ startsWith(secrets.API_KEY, 'prod_') }}
  read-secrets-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - run: echo ${{ startsWith(secrets.API_KEY, 'dev_') }}
  read-secrets-repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ startsWith(secrets.API_KEY, 'repo_') }}
